### ISSUE TITLE
Où recherchez-vous

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#108]
# Tickets
- [ ] #522
- [ ] solinumasso/soliguide#63
- [x] solinumasso/soliguide-before-open-source#4269 
- [x] solinumasso/soliguide-before-open-source#4278 
- [x] solinumasso/soliguide-before-open-source#4438
- [x] solinumasso/soliguide-before-open-source#4474
- [x] solinumasso/soliguide-before-open-source#4463
- [x] solinumasso/soliguide-before-open-source#4660
- [x] solinumasso/soliguide-before-open-source#5069
