### ISSUE TITLE
Que recherchez-vous

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#112]
# Tickets
- [ ] solinumasso/soliguide#111
- [ ] solinumasso/soliguide#110
- [x] #772
- [x] #770 
- [x] #439
- [x] solinumasso/soliguide-before-open-source#4311
- [x] solinumasso/soliguide-before-open-source#4314
- [x] solinumasso/soliguide-before-open-source#4312
- [x] solinumasso/soliguide-before-open-source#4465
- [x] solinumasso/soliguide-before-open-source#4466
- [x] solinumasso/soliguide-before-open-source#4539
- [x] solinumasso/soliguide-before-open-source#4540
- [x] solinumasso/soliguide#81

# Composants UI nécessaires
- [x] Top bar
- [x] Champ input
- [x] Boutons (pour les catégories à mettre en avant)
- [x] Liste (pour les suggestions de besoin et pour la navigation parmi les catégories et les sous-catégories)

# Simplifications si nécessaire
- En attendant la livraison UI du composant "Top bar", on ne permet pas à l'utilisateur de revenir en arrière
