### ISSUE TITLE
Résultats de recherche - Vue Carte - Arrivée sur la page

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#113]
# Description
**En tant** que utilisateur de la nouvelle application ayant effectué une recherche
**Je veux** pouvoir voir mes résultats sur une carte après avoir effectué une recherche
**Pour que** je puisse visualiser directement où se trouvent les structures

# Contexte
- [ ] Faire en sorte que l'utilisateur voit un spinner le temps que les résultats apparaissent sur la carte
- [ ] Faire en sorte que des pins représentent chacune des structures  (et chacun des points de passages des parcours mobiles)
- [ ] Les points de passages des parcours mobiles correspondant à la recherche de l'utilisateur doivent être affiché de la même manière que les structures correspondantes à la rechercher de l'utilisateur. solinumasso/soliguide-before-open-source#4282 est peut-être nécessaire pour cela

## A discuter
- Si plus de 20 structures correspondent à la recherche de l'utilisateur, alors il ne faut en afficher que 20, si nécessaire clusterisées
- Si l'utilisateur clique sur un cluster, alors un zoom est fait de manière à scinder le cluster
- Si l'utilisateur zoome de lui-même, si nécessaire, les clusters se scindent
- Si l'utilisateur dezoome, si nécessaire, les structures se rescindent en cluster

## Hors scope : 
- [x] Le fait de voir la Top Bar pour voir quelle est la recherche et la modifier. C'est le sujet de solinumasso/soliguide-before-open-source#4320 
- [ ] Le fait d'ouvrir une miniature au clic sur un pin. C'est le sujet de solinumasso/soliguide#114 
- [ ] Le fait de voir combien de lieu correspondent à la recherche et d'accéder à la vue liste (Voir la liste des X lieux trouvés). C'est le sujet de solinumasso/soliguide#115 
- [ ] Le fait de permettre à l'utilisateur de centrer la carte sur sa position. C'est le sujet de solinumasso/soliguide#116 
- [ ] Les filtres. C'est le sujet de solinumasso/soliguide#117 

# Maquettes
- [chargement résultats](https://www.figma.com/design/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=9005-33066&m=dev&t=DYvlVmkJnfsMextz-1)
- [résultats sur la carte](https://www.figma.com/design/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=9005-33085&m=dev&t=DYvlVmkJnfsMextz-1)

https://github.com/user-attachments/assets/b7165bd9-5669-41aa-8a33-8df47e5ca2f3

# Composants design system
- [spinner](https://design-system.demo.soliguide.dev/?path=/story/general-spinner--default)
