### ISSUE TITLE
Résultats de recherche - Transverse

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#121]
# Tâches et User Stories
- [ ] solinumasso/soliguide#119
- [ ] solinumasso/soliguide#117 
- [ ] solinumasso/soliguide#83
- [ ] solinumasso/soliguide#120
- [x] solinumasso/soliguide-before-open-source#4320 
- [x] solinumasso/soliguide-before-open-source#4282 
- [x] solinumasso/soliguide-before-open-source#4766
