### ISSUE TITLE
Résultats de recherche - Vue Liste -  Amélioration Card

### ISSUE THREAD

**Issue by AudreySol** [solinumasso/soliguide#128]
# Description

Le but de ce ticket est d'ajouter divers améliorations sur la Card d'une structure afin de traiter des sujets d'accessibilité, d'ergonomie et d'évolutions pour accueillir les favoris :

## 1. Encart Header / accessibilité :
- [ ] ajouter une image en svg ( ⚠ l'image est à récupérer ici et non sur Figma)
- [ ] ajouter un overlay sur cette image avec la variable **OverlayStrong**

![Image](https://github.com/user-attachments/assets/bc22a847-beaf-45ee-9a20-0f3df328aa80)

## 2 Encart Header / réagencement ajout favoris
- [x] passer le bloc tag + horaires au-dessus du Title
- [x] afficher le button favoris à coté du bloc tag+ horaires
- [x] passer l'info source de la donnée en-dessous du Title  et justifier son texte à gauche
- [x] revoir les spacing du Header qui ont changés ( voir les variables en [dév mode Figma](https://www.figma.com/design/WyozCsJNRQ96xfI0z67Adw/Solinum---UI-Kit?node-id=2801-1058&m=dev&t=Z78KSnhqwdOCSPSu-1))

## 3. Encart services / ergonomie + accessibilité
- [ ] Ajouter un **lien cliquable** sur le **+X** lorsqu'il s'affiche
- [ ] Sur ce nouveau lien, prévoir **l'attributs title** avec ce texte : "_Afficher tous les services de la structure_" et prévoir les traductions de ce texte pour le multilingue.
- [ ] Faire en sorte que le **lien renvoi directement à la section des services** de la fiche détaillée
- [ ] Sur le rendu du bloc des services de la card,  ajouter une propriété css flew-start

# Maquette

[https://www.figma.com/design/WyozCsJNRQ96xfI0z67Adw/Solinum---UI-Kit?node-id=2801-1058&m=dev&t=Z78KSnhqwdOCSPSu-1](https://www.figma.com/design/WyozCsJNRQ96xfI0z67Adw/Solinum---UI-Kit?node-id=2801-1058&m=dev&t=Z78KSnhqwdOCSPSu-1)

# Dépendance

- [x] s'occuper des corrections sur le design system #87  avant de faire ces modifications
- [ ] faire les modifs #143 
- [ ] si les modifications ne sont pas trop importantes il est possible de s'occuper totalement ou en partie du ticket #180 en même temps pour régler des problèmes d'accessibilité sur la card
