### ISSUE TITLE
Composant InfoBlock

### ISSUE THREAD

**Issue by AudreySol** [solinumasso/soliguide#132]
# Description

Créer le composant InfoBlock avec toutes ces variantes :

- [x] InfoIcon : #4811
- [x] TextClamper : #4827
- [x] InfoBlock avec TextClamper : #4800
- [x] InfoBlock sans TextClamper : #4801
- [ ] InfoBlock avec Close Button : #140 

# Maquettes

Lien vers le composant InfoBlock : https://www.figma.com/design/WyozCsJNRQ96xfI0z67Adw/Solinum---UI-Kit?node-id=2749-5390&t=g0waXGKwxFVwJmRb-1

Liens vers les icons de l'InfoBlock  : https://www.figma.com/design/WyozCsJNRQ96xfI0z67Adw/Solinum---UI-Kit?node-id=2002-267&t=AQRq6ctOOzxWJtA3-1

**Comment by pYassine** [comment]
@Younes-Kch T'es dessus ?
