### ISSUE TITLE
Résultats de recherche - Vue Liste

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#138]
# Découpage

## A  traiter
- [ ] solinumasso/soliguide#131
- [ ] solinumasso/soliguide#128
- [ ] solinumasso/soliguide#133
- [ ] solinumasso/soliguide#104
- [ ] solinumasso/soliguide#126
- [ ] solinumasso/soliguide#124
- [ ] solinumasso/soliguide#123
- [ ] solinumasso/soliguide#122
- [x] solinumasso/soliguide#134

## Terminés
- [x] solinumasso/soliguide-before-open-source#4649
- [x] solinumasso/soliguide-before-open-source#4650
- [x] solinumasso/soliguide-before-open-source#4651
- [x] solinumasso/soliguide-before-open-source#4949
- [x] solinumasso/soliguide-before-open-source#4831
- [x] solinumasso/soliguide-before-open-source#4652
- [x] solinumasso/soliguide-before-open-source#4653
- [x] solinumasso/soliguide-before-open-source#4655
- [x] solinumasso/soliguide-before-open-source#4443
- [x] solinumasso/soliguide-before-open-source#4947
- [x] solinumasso/soliguide#65
- [x] solinumasso/soliguide#51
- [x] solinumasso/soliguide-before-open-source#4666 
- [x] solinumasso/soliguide-before-open-source#5031
- [x] solinumasso/soliguide#129

# Règles de gestion
## Tags
- **Ouvert** - Anciennement **Ouvert aujourd'hui**
- **Fermé** - Anciennement *Fermé aujourd'hui**
- **Brouillon**
- **Horaires non renseigné** - Quand une structure est en ligne, n'a pas de fermeture temporaire en cours, et n'a pas d'horaires
- **Hors ligne**
- **Ouverture limitée** - Anciennement **Ouvert avec services limités**, correspond à quand un service est ouvert aujourd'hui alors que la structure est fermée
- **Fermeture temporaire** - Nouveau tag, quand une structure a une fermeture temporaire en cours
- **Fermeture définitive** - Nouveau tag

### Tests déjà menés
- Structure nouvellement créée sans horaires --> 👍 Apparait bien avec le tag **Horaires non renseignés**
- Structure en ligne à laquelle on enlève les horaires --> 👍 Apparait bien avec le taf **Horaires non renseignés**
- Structure ouverte aujourd'hui --> 👍  Apparait bien avec le tag **Ouvert**
- Structure fermée aujourd'hui --> 👍 Apparait bien avec le taf **Fermé**
- Structures ouverte aujourd'hui avec une fermeture temporaire prévue --> 👍 Apparait bien avec le tag **Ouvert**
- Structure ouverte aujourd'hui avec une fermeture temporaire en cours --> 👍 Apparait bien avec le tag **Fermé temporairement**
- Structures ouverte aujourd'hui avec une fermeture temporaire qui vient de terminer
- Structure fermée aujourd'hui avec une fermeture temporaire prévue 
- Structure fermée aujourd'hui avec une fermeture temporaire en cours
- Structure fermée aujourd'hui avec une fermeture temporaire qui vient de terminer

### Problématiques identifiées lors des tests du 27 septembre
- Une structure ouverte vendredi avec une fermeture temporaire commençant le lundi suivant s'affiche comme étant fermée temporairement, alors qu'elle devrait s'afficher comme ouverte aujourd'hui (avec, dans la version actuelle, un bandeau indiquant qu'une fermeture temporaire va débuter)
Ces règles ont été partiellement implémenté.
Prochaine étape : on le met en test et Gabriel le revoit avec Samuel

## Titre
- Si le titre comporte trop de caractères pour la largeur de l'écran, il s'affiche sur une ligne et termine par "..."

## Horaires du jour
- Si la structure est ouverte aujourd'hui, qu'il n'y a pas de fermeture temporaire en cours, afficher les horaires du jours sous le format : **Aujourd'hui : 10h30 à 12h - 14h à 17h30**
- Si la structure a une fermeture temporaire en cours, afficher la fourchette de fermeture temporaires sous le format suivant : **Fermeture : 01/07/2024 au 31/08/2024**
- Si le libellé comporte trop de caractères pour la largeur de l'écran, il s'affiche sur une ligne et termine par "..."
- Si la structure est ouverte avec services limités, si elle est fermée sans fermeture temporaire, si c'est un brouillon, si elle n'a pas d'horaires renseignés, si elle est hors ligne, si elle est fermée définitivement : ne pas afficher d'horaires

## Adresse
- L'adresse doit se limiter au code postal et à la ville si elle est marquée comme étant sur orientation dans les modalités d'accès
- Si la structure n'est pas marqué sur orientation, l'adresse doit s'afficher entièrement. Notamment, si un complément d'adresse a été renseigné, il doit être affiché à la suite de l'adresse, séparé d'un tiret : **13 rue Santeuil, 75006 Paris - Bureaux 418 et 419**
- Si le libellé comporte trop de caractères pour la largeur de l'écran, il s'affiche sur une ligne et termine par "..."

## Distance
La distance entre l'utilisateur et l'adresse de la structure doit s'afficher dans les conditions suivantes : 
- La recherche a été faite suivant une adresse précise
- La structure n'est pas sur orientation

On aimerait rajouter dans ces conditions le fait que la structure doit avoir une adresse précise (ex : l'adresse de la structure n'est pas **70014 Paris**), mais c'est difficilement implémentable pour le moment

## Bouton de navigation
- Le bouton de navigation s'affiche grisé lorsque la structure est sur orientation ou que l'adresse n'est pas renseignée

On aimerait rajouter dans ces conditions le fait que la structure doit avoir une adresse précise (ex : l'adresse de la structure n'est pas **70014 Paris**), mais c'est difficilement implémentable pour le moment

- Au clic sur le bouton de navigation, je suis redirigé vers l'application de navigation de mon téléphone, qui "pointe" sur l'adresse de la structure. Si j'ai plusieurs applications de navigation, Soliguide me demande dans quelle application je veux ouvrir la navigation
![image](https://github.com/user-attachments/assets/ddbecc2c-8e32-4f8f-b995-c04f0bac3473)

## Bouton Appeler
- Cas où il n'y a pas de numéro de téléphone : le bouton s'affiche grisé
- Cas où il y a un numéro de téléphone : le bouton s'affiche. Au clic, l'appel est lancé
- Cas où il y a plus d'un numéro de téléphone : le bouton s'affiche. Au clic, le bottom sheet s'ouvre, et propose les différents numéros. Au clic sur un numéro, l'appel est lancé. Au clic sur **Appeler**, le bottom sheet se ferme. Dépendance avec le compostant Bottom sheet qui n'est pas encore implémenté

### Tags
- **Réservé aux pro** -- Cela devient un message additionnel
