### ISSUE TITLE
Nouvelle application mobile - Design System

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#141]
# Tickets

### Tickets à traiter
- [ ] solinumasso/soliguide#143
- [ ] solinumasso/soliguide#64
- [ ] solinumasso/soliguide#132
- [ ] #381
- [ ] #272
- [ ] solinumasso/soliguide#127
- [x] solinumasso/soliguide#142

### Tickets terminés
- [x] solinumasso/soliguide-before-open-source#4252
- [x] solinumasso/soliguide-before-open-source#4290
- [x] solinumasso/soliguide-before-open-source#4291
- [x] solinumasso/soliguide-before-open-source#4328
- [x] solinumasso/soliguide-before-open-source#4339
- [x] solinumasso/soliguide-before-open-source#4342
- [x] solinumasso/soliguide-before-open-source#4393
- [x] solinumasso/soliguide-before-open-source#4361
- [x] solinumasso/soliguide-before-open-source#4472
- [x] solinumasso/soliguide-before-open-source#4484
- [x] solinumasso/soliguide-before-open-source#4364
- [x] solinumasso/soliguide-before-open-source#4384
- [x] solinumasso/soliguide-before-open-source#4656
- [x] solinumasso/soliguide-before-open-source#4502 
- [x] solinumasso/soliguide-before-open-source#4884
- [x] solinumasso/soliguide-before-open-source#4537
- [x] solinumasso/soliguide-before-open-source#4567
- [x] solinumasso/soliguide#144
- [x] solinumasso/soliguide#87
