### ISSUE TITLE
Fiche

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#151]
# Tâches et User Stories

## A traiter 
- [ ] #526
- [ ] solinumasso/soliguide#69
- [ ] solinumasso/soliguide#103
- [ ] #436
- [ ] solinumasso/soliguide#158
- [ ] solinumasso/soliguide#156
- [ ] solinumasso/soliguide#152
- [ ] solinumasso/soliguide#153
- [ ] solinumasso/soliguide#159
- [ ] solinumasso/soliguide#146
- [ ] solinumasso/soliguide#161
- [ ] solinumasso/soliguide#155
- [ ] solinumasso/soliguide#154
- [ ] solinumasso/soliguide#162
- [ ] #935
- [x] solinumasso/soliguide#150

## Terminés
- [x] solinumasso/soliguide-before-open-source#4667
- [x] solinumasso/soliguide#125
- [x] solinumasso/soliguide-before-open-source#4897 
- [x] solinumasso/soliguide-before-open-source#4669
- [x] solinumasso/soliguide-before-open-source#4670
- [x] solinumasso/soliguide-before-open-source#4671
- [x] solinumasso/soliguide-before-open-source#4673
- [x] solinumasso/soliguide-before-open-source#4672
- [x] solinumasso/soliguide-before-open-source#4674 
- [x] solinumasso/soliguide-before-open-source#4837 
- [x] solinumasso/soliguide-before-open-source#4829
- [x] solinumasso/soliguide-before-open-source#4746
- [x] solinumasso/soliguide#67
- [x] solinumasso/soliguide-before-open-source#4681
- [x] solinumasso/soliguide-before-open-source#5227
- [x] solinumasso/soliguide-before-open-source#4678
- [x] solinumasso/soliguide-before-open-source#5128
- [x] solinumasso/soliguide-before-open-source#4680
- [x] solinumasso/soliguide-before-open-source#4675
- [x] solinumasso/soliguide-before-open-source#5129
- [x] solinumasso/soliguide-before-open-source#4677
- [x] solinumasso/soliguide-before-open-source#4508
- [x] solinumasso/soliguide-before-open-source#4523
- [x] solinumasso/soliguide-before-open-source#4509
- [x] solinumasso/soliguide-before-open-source#4510
- [x] solinumasso/soliguide-before-open-source#4516
- [x] solinumasso/soliguide-before-open-source#4517
- [x] solinumasso/soliguide-before-open-source#4640
- [x] solinumasso/soliguide-before-open-source#4741
- [x] solinumasso/soliguide#59
- [x] solinumasso/soliguide-before-open-source#5030
- [x] solinumasso/soliguide#157

# Règles de gestion
### Tags
Mêmes règles que dans solinumasso/soliguide#138 
### Horaires du jour
Mêmes règles que dans solinumasso/soliguide#138 

### Bouton Appeler
Mêmes règles que dans solinumasso/soliguide#138 

### Adresse
- L'adresse doit se limiter au code postal et à la ville si elle est marquée comme étant sur orientation dans les modalités d'accès
- Si la structure n'est pas marqué sur orientation, l'adresse doit s'afficher entièrement. Notamment, si un complément d'adresse a été renseigné, il doit être affiché à la suite de l'adresse, séparé d'un tiret : 13 rue Santeuil, 75006 Paris - Bureaux 418 et 419
Si le libellé comporte trop de caractères pour la largeur de l'écran disponible pour afficher l'adresse (prendre en compte qu'il y a un bouton permettant de copier, donc la largeur disponible est réduire), il s'affiche sur une ligne et termine par "..."
### Bouton Afficher l'adresse
- Au clic, ouvre le Bottom Sheet (ticket en cours de création dans solinumasso/soliguide#141 ) comme montré [ici](https://www.figma.com/design/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=5323-20548&t=8MSkCMuo2RonFy3Q-1); Sur le Bottom Sheet, un lien permet d'ouvrir cette adresse sur une application de cartographie
- Nice-To-Have : peut-on n'afficher ce bouton que si l'adresse ne rentre pas sur la largeur qui lui est réservée (et termine donc par "...")
### Bouton Voir sur la carte
- Ne s'affiche pas si la structure est marquée comme étant sur orientation dans les modalités d'accès
- Permet d'ouvrir l'adresse sur une application de cartographie
### Bouton Accès en transport
- Ce bouton ne s'affiche pas pour le moment, ça sera l'objet d'un autre ticket

## Horaires
- Cas des horaires temporaires en cours : l'utilisateur voit les horaires temporaires, est alerté qu'il s'agit d'horaires temporaires, et peut accéder aux horaires habituels. Maquette [ici](https://www.figma.com/design/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=4089-11391&t=1Sl7YYveo4mG3f7x-1), mais elle ne permet pas d'afficher les horaires habituels. A voir si c'est pertinent d'afficher des horaires habituels
- Cas des horaires temporaires à venir : aujourd'hui, si des horaires temporaires sont prévus pour dans moins de 2 semaines, ils sont affichés par défaut sur la fiche, avec la possibilité de revenir aux horaires habituels. A moins que ça soit compliqué, je ne propose de ne pas afficher des horaires temporaires à venir
- Cas d'une fermeture temporaires en cours 
- Cas d'une fermeture temporaire à venir
- Cas des horaires non renseignés

# Pièces jointes et captures
- https://www.figma.com/design/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=4085-11311&m=dev&t=9iYn1haZOrfpN85A-1
