### ISSUE TITLE
Transverse

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#167]
# Tâches et User Stories
- [ ] solinumasso/soliguide#164 
- [x] solinumasso/soliguide#68
- [x] solinumasso/soliguide-before-open-source#5280
- [x] #324
- [x] #456
- [x] solinumasso/soliguide#165
- [ ] solinumasso/soliguide#166
- [x] solinumasso/soliguide-before-open-source#4697
- [x] solinumasso/soliguide#75
- [ ] solinumasso/soliguide#101
- [x] solinumasso/soliguide-before-open-source#4978
- [x] solinumasso/soliguide-before-open-source#5114
- [ ] solinumasso/soliguide#145
- [ ] solinumasso/soliguide#168 
- [ ] solinumasso/soliguide#169
- [ ] solinumasso/soliguide#170
- [ ] #314
