### ISSUE TITLE
Sujets à traiter ensuite

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#171]
# Description
Voici une liste de sujets à analyser puis à mettre dans le backlog : 
- [ ] Plusieurs numéros de téléphone : solinumasso/soliguide#126 + solinumasso/soliguide#146 
- [ ] Filtres ouvert aujourd'hui, accessible aux PMRs, animaux acceptés : solinumasso/soliguide#117 
- [ ] solinumasso/soliguide#131 
- [ ] Message d'erreur lorsque API down ou géolocalisation refusée solinumasso/soliguide#131 et solinumasso/soliguide#63 
- [ ] Identifier au premier coup d'oeil les services dont les horaires / conditions d'accès / publics cibles sont différents (pour éviter que l'utilisateur pense que les conditions de la structure correspondent à celle du service) : solinumasso/soliguide-before-open-source#4741 
- [ ] Indiquer non présence / présence limitée sur un territoire non déployé / un territoire Guid'Alim
