### ISSUE TITLE
Déploiement Soliguide à la Réunion

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#198]
# Tâches et User Stories
- [x] solinumasso/soliguide-before-open-source#3141 
- [ ] solinumasso/soliguide#200 
- [x] solinumasso/soliguide-before-open-source#3143 
- [x] solinumasso/soliguide-before-open-source#3144 
- [ ] solinumasso/soliguide#199 
- [x] solinumasso/soliguide-before-open-source#3151 
- [x] solinumasso/soliguide-before-open-source#3329
