### ISSUE TITLE
🇪🇸 Déploiement Soliguide Espagne & Andorre

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#222]
# Tâches et User Stories

## Taxonomie
- [x] #706
- [x] #673 
- [x] #796
- [x] #277
- [x] #297
- [ ] #473
- [ ] #298
- [ ] #299
- [ ] #321
- [x] #349
- [x] #374
- [ ] #475
- [x] #648

## Application mobile
- [ ] #36 

## Autres sujets
- [ ] #882
- [ ] #320
- [ ] #326
- [ ] #365
- [ ] #371
- [ ] #398

## Exclusif à l'Internationalisation - v1

- [x] solinumasso/soliguide-before-open-source#3525
- [x] solinumasso/soliguide-before-open-source#3527
- [x] solinumasso/soliguide-before-open-source#3646
- [x] solinumasso/soliguide-before-open-source#3680 
- [x] solinumasso/soliguide-before-open-source#3139 
- [x] solinumasso/soliguide-before-open-source#3482
- [x] solinumasso/soliguide-before-open-source#3457
- [x] solinumasso/soliguide-before-open-source#3450
- [x] solinumasso/soliguide-before-open-source#3190 
- [x] solinumasso/soliguide-before-open-source#3191
- [x] solinumasso/soliguide-before-open-source#3192
- [x] solinumasso/soliguide-before-open-source#3549
- [x] solinumasso/soliguide-before-open-source#3550
- [x] solinumasso/soliguide-before-open-source#3551
- [x] solinumasso/soliguide-before-open-source#3121
- [x] solinumasso/soliguide-before-open-source#3193
- [x] solinumasso/soliguide-before-open-source#3196
- [x] solinumasso/soliguide-before-open-source#3393
- [x] solinumasso/soliguide-before-open-source#3394
- [x] solinumasso/soliguide-before-open-source#3598
- [x] solinumasso/soliguide-before-open-source#3620
- [x] solinumasso/soliguide-before-open-source#3519 
- [x] solinumasso/soliguide-before-open-source#3538 
- [x] solinumasso/soliguide-before-open-source#3458
- [x] solinumasso/soliguide-before-open-source#3456
- [x] solinumasso/soliguide-before-open-source#3564
- [x] solinumasso/soliguide-before-open-source#3689
- [x] solinumasso/soliguide-before-open-source#3904
- [x] solinumasso/soliguide-before-open-source#3891

## Exclusif à l'Internationalisation - Post v1

- [x] solinumasso/soliguide-before-open-source#3949
- [x] solinumasso/soliguide-before-open-source#3913
- [x] solinumasso/soliguide-before-open-source#3774
- [x] solinumasso/soliguide-before-open-source#3152
- [x] solinumasso/soliguide-before-open-source#3261
- [x] solinumasso/soliguide-before-open-source#3517
- [x] solinumasso/soliguide-before-open-source#3535
- [x] solinumasso/soliguide-before-open-source#3616
- [x] solinumasso/soliguide-before-open-source#3960
- [x] solinumasso/soliguide-before-open-source#3997 
- [x] solinumasso/soliguide-before-open-source#3910
- [x] solinumasso/soliguide-before-open-source#4395
- [x] solinumasso/soliguide-before-open-source#3954
- [x] solinumasso/soliguide-before-open-source#4522 
- [x] solinumasso/soliguide-before-open-source#4547
- [x] solinumasso/soliguide-before-open-source#3871
- [x] solinumasso/soliguide-before-open-source#3853
- [x] solinumasso/soliguide-before-open-source#3272
- [x] solinumasso/soliguide-before-open-source#4890
- [x] solinumasso/soliguide-before-open-source#3328
- [x] solinumasso/soliguide-before-open-source#3909
- [x] solinumasso/soliguide-before-open-source#3920
- [x] solinumasso/soliguide-before-open-source#3919
- [x] solinumasso/soliguide-before-open-source#3918
- [x] solinumasso/soliguide-before-open-source#3912
- [x] solinumasso/soliguide-before-open-source#3915 
- [x] solinumasso/soliguide-before-open-source#3988
- [x] solinumasso/soliguide-before-open-source#4433
- [x] solinumasso/soliguide-before-open-source#3194
- [ ] solinumasso/soliguide#223
- [ ] solinumasso/soliguide#224
- [x] solinumasso/soliguide-before-open-source#3518
- [ ] solinumasso/soliguide#80
- [x] solinumasso/soliguide#62
- [ ] solinumasso/soliguide#225
- [x] solinumasso/soliguide-before-open-source#3961
- [ ] solinumasso/soliguide#226
- [x] solinumasso/soliguide-before-open-source#4873
- [x] solinumasso/soliguide-before-open-source#4875
- [x] solinumasso/soliguide-before-open-source#3911
- [x] solinumasso/soliguide-before-open-source#4624
- [ ] solinumasso/soliguide#227
- [x] solinumasso/soliguide-before-open-source#4535 

## Global à Soliguide - v1

- [x] solinumasso/soliguide-before-open-source#3116 
- [x] solinumasso/soliguide-before-open-source#3150
- [x] solinumasso/soliguide-before-open-source#3271
- [x] solinumasso/soliguide-before-open-source#3226
- [x] solinumasso/soliguide-before-open-source#3158
- [x] solinumasso/soliguide-before-open-source#3188
- [x] solinumasso/soliguide-before-open-source#3343
- [x] solinumasso/soliguide-before-open-source#3359
- [x] solinumasso/soliguide-before-open-source#3604
- [x] solinumasso/soliguide-before-open-source#3759
- [ ] Page de maintenance pour Soliguia
- [ ] Page d'aide pour Soliguia
- [x] solinumasso/soliguide#228
- [ ] solinumasso/soliguide#229

## Global à Soliguide - Post v1

- [x] solinumasso/soliguide-before-open-source#3760
- [x] solinumasso/soliguide-before-open-source#3863
- [x] solinumasso/soliguide-before-open-source#3342
- [x] solinumasso/soliguide-before-open-source#3265
- [x] solinumasso/soliguide-before-open-source#3848
- [x] solinumasso/soliguide-before-open-source#3866
- [ ] solinumasso/soliguide#231
- [ ] solinumasso/soliguide#230 
- [x] solinumasso/soliguide-before-open-source#4781
- [ ] solinumasso/soliguide#232
- [ ] solinumasso/soliguide#233

### Dette technique

- [x] solinumasso/soliguide-before-open-source#4154
- [x] solinumasso/soliguide-before-open-source#3287 
- [x] solinumasso/soliguide-before-open-source#4607
- [ ] solinumasso/soliguide#234
- [ ] Enlever les propriété en français dans `areas`
- [ ] Supprimer `slugs` de `LocationsAreas`
- [ ] Typer les lieux et services
- [ ] Adapter la MàJ à l'Espagne et l'Andorre
- [ ] Déplacer les champs de MàJ dans une ou plusieurs collections dédiées

# Informations intéressantes

- Est-ce qu'on veut qu'un utilisateur à la frontière puisse chercher à la fois des structures françaises, à la fois des structures espagnoles ? Oui. [Conversation Slack](https://solinum.slack.com/archives/C04A96901RN/p1704896266739809). [Bloc Notion](https://www.notion.so/solinum/Strat-gie-de-d-veloppement-Catalunya-i-Andorra-2026-7e56b005ed874c728880d12fc697f5aa?pvs=4#0f4d71f62c374691ae5070cfa0ab3266) à ce sujet
- Est-ce qu'on envisage qu'un utilisateur français puisse créer une structure en France et en Espagne ? Oui, mais pas prioritaire. [Conversation Slack](https://solinum.slack.com/archives/C04A96901RN/p1704896266739809)
- [Boite à questions Gabriel](https://docs.google.com/document/d/1fvXmy4hfib4QMOt0L8cy1und-8oiq6OK0vAJdXpp4ww/edit)

# Problématiques identifiées lors des tests
- J'ai envoyé une invitation à un pro. Lorsque je soumet le formulaire d'activation de compte pro, j'ai une erreur --> OK
![image](https://github.com/solinumasso/soliguide/assets/150792389/df6de482-f905-4e6d-b5d6-b5854673564b)

- Quand je crée une nouvelle structure Soliguia, le fond de carte me propose par défaut une zone à Paris --> OK, ticket créé : solinumasso/soliguide-before-open-source#3912 
![image](https://github.com/solinumasso/soliguide/assets/150792389/89261d62-2090-4731-a69c-bc77c844733e)
- Je ne peux pas trouver l'adresse Paseo de Gracia 43 de Barcelone. Pourtant c'est une adresse valide
![image](https://github.com/solinumasso/soliguide/assets/150792389/85279cec-33c0-4c4c-9825-a1ea1e4cd388)
![image](https://github.com/solinumasso/soliguide/assets/150792389/f02ddaf3-5781-4f84-852d-4d35322b0b9d)
- Sur l'interface qui permet de définir les horaires, certains jours de la semaine sont affichés en minuscules sans majuscule au début. De plus, certains jours de la semaine sont affichés tout en majuscules. Il faudrait idéalement que la première lettre soit en majuscule, les suivantes en minuscules. C'est un souci Weblate. J'ai modifié le 21 mai les traductions de lundi et mardi pour qu'elles soient à la bonne nommenclature (première lettre en majuscule, lettres suivantes en minuscules). Vérifier dans quelques jours que c'est bien pris en compte --> OK
![image](https://github.com/solinumasso/soliguide/assets/150792389/94b33ee3-d3cb-4efc-b134-46e42e174550)
- Pas un bug en soit mais à garder en tête. On demande si les produits sont d'origine française, alors qu'on est en Espagne ou Andorre --> OK, ticket créé : solinumasso/soliguide-before-open-source#3911 
![image](https://github.com/solinumasso/soliguide/assets/150792389/553f0be8-6f52-41b0-83a4-8dcb036daf7e)
- Je ne peux pas saisir de photos dans la section correspondante --> OK
![image](https://github.com/solinumasso/soliguide/assets/150792389/3c53695c-7e44-4e42-8301-0db36af9e176)
- Quand je vais sur le Manage Organisation avec gabriel@soliguia.es, aucun département n'est sélectionné. Peut-être qu'il y a le même problème sur Soliguide --> A voir avec Léna, je lui ai demandé
![image](https://github.com/solinumasso/soliguide/assets/150792389/911b1382-173d-45b9-a36e-3531a40cebd8)
- Pourquoi y a-t-il une entrée **CREATE_A_USER** ? Elle n'apparait pas sur Soliguide France --> OK
![image](https://github.com/solinumasso/soliguide/assets/150792389/7d255579-8d65-4735-b02e-38b8ee57fc55)
- Quand j'essaie de créer une porteuse externe sur le territoire de Gérone via l'URL */register*, je suis redirigé vers la page d'accueil avec cette erreur. Quand je fais un reset mot de passe avec l'email du compte, je ne reçois aucun email --> OK
![image](https://github.com/solinumasso/soliguide/assets/150792389/a2b59060-af9f-40e9-af3a-e0e1f382fb2a)
- Dans le Manage Organisation français, les département 01 à 09 ressortent en dernier au lieu de ressortir en premier --> OK
![image](https://github.com/solinumasso/soliguide/assets/150792389/c6d02b3e-2405-48ae-907e-77d9c6c2ef49)
- La langue parlé s'appelle **Catalan; Valencien**. Peut-on faire en sorte que ça s'appelle juste **Catalan** ?
![image](https://github.com/solinumasso/soliguide/assets/150792389/3cf1feec-bbce-4ce6-b32b-70099fe87b24)
- Le terme **Soliguide** est reprise à plusieurs endroits en dur. Peut-on le remplacer par Soliguia ?
![image](https://github.com/solinumasso/soliguide/assets/150792389/0aca60fc-b715-4826-8096-a3c22e48e93a)
- Les menus Soligare et Traductions apparaissent pour les porteurs internes et externes
![image](https://github.com/solinumasso/soliguide/assets/150792389/ce15bae5-0f27-4311-8009-54cfb4fcfda8)

# Reste à tester
- Réinitialisation de mot de passe
