### ISSUE TITLE
Modif couleurs variables👍

### ISSUE THREAD

**Issue by AudreySol** [solinumasso/soliguide#280]
###  Interaction colors

**Interaction Highlight primary**

- [x] remplacer le code héxa de la variable **interactionHighlightPrimaryHover** par **#FA6D56**

**Interaction Highlight secondary**

- [x] remplacer le code héxa de la variable **interactionHighlightSecondary** par **#613677**
- [x] remplacer le code héxa de la variable **interactionHighlightSecondaryHover** par **#463351**
- [x] remplacer le code héxa de la variable **interactionHighlightSecondaryPress** par **#271332**

**Interaction Neutral**

- [x] remplacer le code héxa de la variable **interactionNeutral** par **#271332**
- [x] remplacer le code héxa de la variable **interactionNeutralHover** par **#463351**

**Interaction Outlined Secondary**

- [x] remplacer le code héxa de la variable **interactionOutlinedSecondaryHover** par **#F6EDFA**
- [x] remplacer le code héxa de la variable **interactionOutlinedSecondaryPress** par **#DFBCEB**
- [x] remplacer le code héxa de la variable **interactionOutlinedSecondaryActive** par **#613677**
- [x] remplacer le code héxa de la variable **interactionOutlinedSecondaryActiveHover** par **#463351**
- [x] remplacer le code héxa de la variable **interactionOutlinedSecondaryActivePress** par **#271332**

**Interaction Reversed**

- [x] remplacer le code héxa de la variable **interactionReversedPress** par **#FDB8AD**
- [x] remplacer le code héxa de la variable **interactionReversedActivePress** par **#882314**

### Text colors

- [x] remplacer le code héxa de la variable **textHighlightSecondary** avec le code héxa **#613677**
- [x] créer une variable **textHighlightSecondary2** avec le code héxa **#271332**
- [x] créer une variable **textHighlightPrimary2** avec le code hexa **#C8260D**
- [x] remplacer le code héxa de la variable **textSucess** par **#047857**
- [x] remplacer le code héxa de la variable **textWarning** par **#BE8204**
- [x] remplacer le code héxa de la variable **textError** par **#D32F2F**

### Gradients

- [x] renommer **gradientSecondary** par **gradientTertiary**
- [x] changer le dégradé de **gradientTertiary** : linear-gradient(270deg, **#504EB4** 0%, **#3B3D74** 100%)
- [x] ajouter un nouveau gradient **gradientSecondary** (après avoir renommée l'ancien) : linear-gradient(270deg, **#613677** 0%, **#463351** 100%)

### Surface colors

**Surface Overlay**

- [x] ajouter une nouvelle variable **overlayVerystrong** avec **rgba(38, 38, 38, 0.7)**

**Surface primary**

- [x] remplacer le code héxa de la variable **surfacePrimary3** par **#FDB8AD**
- [x] créer une variable **surfacePrimary4** avec le code héxa **#FA6D56**
- [x] créer une variable **surfacePrimary5** avec le code héxa **#ED3215**

**Surface secondary**

- [x] renommer la variable **surfaceSecondary1** pour **surfaceTertiary1**
- [x] renommer la variable **surfaceSecondary2** pour **surfaceTertiary2**
- [x] renommer la variable **surfaceSecondary3** pour **surfaceTertiary3**
- [x] renommer la variable **surfaceSecondary4** pour **surfaceTertiary4**
- [x] renommer la variable **surfaceSecondaryGradient** pour **surfaceTertiaryGradient**
- [x] finir par déplacer ces variables dans la section **surface tertiary**

**Surface tertiary**

- [x] renommer la variable **surfaceTertiary1** pour **surfaceSecondary1**
- [x] créer une variable **surfaceSecondary2** avec le code héxa **#ECD9F5**
- [x] créer une variable **surfaceSecondary3** avec le code héxa **#A165C3**
- [x] créer une variable **surfaceSecondaryGradient**(après avoir renommée l'ancienne) et ajouter le nouveau **gradientSecondary**
- [x] finir par déplacer ces variables dans la section **surface Secondary**

### Border colors

- [x] remplacer le code héxa de la variable **borderError** par **#DC2626**
- [x] remplacer le code héxa de la variable **borderSucess** par **#059669**

**Comment by AudreySol** [comment]
J'ai oubliée de remonter 2 modifs de variables dans le ticket :
- TextHiglightTertiary : #424291
- SurfaceSecondary2 : #DFBCEB

Et le rendu du **OverlayVerystrong** semble bizarre car blanc alors qu'il est sensé être plus foncé que la variable **OverlayStrong**
