### ISSUE TITLE
Nouvelle application mobile

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#45]
# Tickets fonctionnels
- [x] solinumasso/soliguide-before-open-source#4615
- [ ] solinumasso/soliguide#46
- [ ] solinumasso/soliguide#52
- [ ] solinumasso/soliguide#60
- [x] solinumasso/soliguide-before-open-source#4941
- [ ] solinumasso/soliguide#108
- [ ] solinumasso/soliguide#112
- [ ] solinumasso/soliguide#135
- [ ] solinumasso/soliguide#151
- [x] #399
- [x] #337
- [ ] solinumasso/soliguide#149
- [x] solinumasso/soliguide#163
- [ ] solinumasso/soliguide#167
- [x] solinumasso/soliguide#171
- [ ] solinumasso/soliguide#172
- [ ] solinumasso/soliguide#184
- [ ] solinumasso/soliguide#186
- [ ] solinumasso/soliguide#191
- [ ] solinumasso/soliguide#192
- [ ] solinumasso/soliguide#36

# Tickets techniques
- [x] solinumasso/soliguide-before-open-source#4341 
- [ ] solinumasso/soliguide#193

# Ressources
- [Prototype animé](https://www.figma.com/proto/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=2692-6343&t=B2dgtazaXF2mb3q0-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=2340%3A4899)
- [Delivery](https://www.figma.com/design/wZtUJ3duUd77X9gT1EtUbR/Nouvelle-app-Soliguide?node-id=2302-4946)
