### ISSUE TITLE
Arrivée sur l'application et choix de la langue

### ISSUE THREAD

**Issue by gabriel-slnm** [solinumasso/soliguide#46]
# Tickets
- [ ] solinumasso/soliguide#49
- [x] solinumasso/soliguide-before-open-source#4265 
- [x] solinumasso/soliguide-before-open-source#4442
- [x] solinumasso/soliguide-before-open-source#4598
- [x] solinumasso/soliguide-before-open-source#4663
- [x] solinumasso/soliguide-before-open-source#4810
